# Generated by Django 5.2.1 on 2025-05-27 13:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_prod', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('descricao', models.CharField(max_length=45)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categoria', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedi', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('mesa', models.IntegerField()),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Preparando', 'Preparando'), ('Fechado', 'Fechado')], default='Aberto', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='pessoas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id_item_pedi', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='produtos_pedidos.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='produtos_pedidos.produto')),
            ],
        ),
    ]
