# Generated by Django 5.2.1 on 2025-05-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos_pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.CharField(default='https://i0.wp.com/folhameaipe.com/wp-content/uploads/2025/03/Receita-moqueca-capixaba.webp', max_length=255),
            preserve_default=False,
        ),
    ]
