# Generated by Django 5.2.1 on 2025-06-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos_pedidos', '0002_remove_produto_categoria_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
