# Generated by Django 5.2.1 on 2025-05-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='id_pess',
            new_name='pessoa',
        ),
    ]
