# Generated by Django 5.2.1 on 2025-05-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_alter_cliente_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.CharField(default='email@exemplo.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='endereco',
            field=models.CharField(default='Rua Exemplo, 123', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(default='1234', max_length=15),
            preserve_default=False,
        ),
    ]
